### PR TITLE
Fix docker build 

### PR DESCRIPTION
**Pull request by kataev**
Master dockerfile dont build any way.
Reason:
```
curl https://static.rust-lang.org/rustup.sh

#!/bin/bash
echo "The location of rustup.sh has moved."
echo "Run the following command to install from the new location:"
echo "    curl https://sh.rustup.rs -sSf | sh"
```

### CODE REVIEW

**Comment by Mythra** [comment]
Thanks for catching this! Are you okay to sign the CLA so we can merge this?

**Comment by Mythra** [comment]
@kataev Any update on the CLA?

**Comment by kataev** [comment]
Just a second...

**Comment by kataev** [comment]
Signed, wait for checks

**Comment by Mythra** [comment]
Thanks @kataev ,

The check is still yellow cause it seems the git email is different from the one you used on github, but since you've confirmed you've signed here I'm going to go ahead, and merge this. In the future for it to be picked up you'll want to ensure those emails are the same.

Thanks very much for your contribution!

**Pull request merged**
